version: "3.7"

services:
  docker-hub:
    image: registry:2
    restart: always
    ports:
      # - 5000:5000
      - 443:443
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/docker-hub.kittymeow.cc.crt
      REGISTRY_HTTP_TLS_KEY: /certs/docker-hub.kittymeow.cc.key
      REGISTRY_HTTP_SECRET: docker-hub.kittymeow.cc
      REGISTRY_HTTP_ADDR: 0.0.0.0:443
    volumes:
      - ./certs:/certs
      - ./docker-hub/conf:/etc/docker/registry
      - ./registry-data:/var/lib/registry

  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: gitlab.kittymeow.cc
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.kittymeow.cc:10443'
        gitlab_rails['gitlab_shell_ssh_port'] = 1022
        gitlab_rails['registry_enabled'] = true
        gitlab_rails['registry_host'] = "docker-hub.kittymeow.cc"
        gitlab_rails['registry_port'] = "443"
        gitlab_rails['registry_api_url'] = "https://docker-hub:443"
        gitlab_rails['registry_key_path'] = "/etc/gitlab/ssl/docker-hub.kittymeow.cc.key"
        gitlab_rails['registry_path'] = "/var/lib/registry"
        gitlab_rails['registry_issuer'] = "symantec"
    ports:
      - 10443:10443
      - 1022:22
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
      - ./certs:/etc/gitlab/ssl
      - ./registry-data:/var/lib/registry
