version: "3.7"

services:
  consul_client:
    image: consul
    environment:
      CONSUL_CLIENT_INTERFACE: eth0
      CONSUL_BIND_INTERFACE: eth0
    volumes:
      - ./data:/consul/data
      - ./consul.d:/consul/config
    command: consul agent -enable-local-script-checks -config-dir=/consul/config -data-dir=/consul/data -retry-join=192.168.254.7:8301 -bind=192.168.254.10 -http-port=28500 -dns-port=28600 -serf-lan-port=28301 -serf-wan-port=28302 -server-port=28300
    network_mode: host

  nodejs:
    build: ./nodejs
    ports:
      - 3000

  swoole:
    build: ./swoole
    ports:
      - 9501
